config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :users, only: %i[new create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  resources :posts, only: %i[index new create]
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  before_create :create_new_token
  has_secure_password
  has_many :posts

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.digest(string)
    Digest::SHA1.hexdigest(string.to_s)
  end

  def create_new_token
    self.remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :signed_in, only: %i[new create]

  def index
    @posts = Post.paginate(page: params[:page],
                           per_page: 5).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = 'Rumour posted !'
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def signed_in
    unless logged_in?
      flash[:danger] = 'Please Sign in.'
      redirect_to login_path
    end
end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def index; end

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'Welcome to Members Only'
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    sign_out if logged_in?
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remember the user session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h2><%= link_to "Members Only", root_path, id: "logo"%></h2>
      <nav class="nav-container">
          <ul class="nav navbar-nav navbar-right flex-row ul-container">
          <% if logged_in? %>
              <li class="list-item"><%= link_to "Post", new_post_path %> </li>
              <li class="list-item "><%= link_to "Log Out", logout_path, method: :delete %></li>
            <% else %>
              <li class="list-item "><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
     <%# @posts.each do |post| %>
       <div class="card-container">
          <div class="cards  animated bounceInLeft">
            <% if logged_in? %>
             <div class="author">  By <%= post.user.name %></div>
               <% else %>
              <div class="author">By (secret)</div>
            <% end %>
            <div class="content">
               <p>Title: <%= post.title %></p>
              
               <p> <%= post.body %></p>
            </div>
            <p class="date">Created on: <%= post.created_at.strftime("%Y-%m-%d at %H:%M:%S") %></p>
          </div>
       </div>
      <%# end %>
     <%#= link_to "create new post" %>

app/views/posts/index.html.erb
  <div class="container main-container">
       <% flash.each do |message_type, message| %>
          <div class="<%= message_type %>"><%= message %></div>
        <% end %>
      <h1>Share a secret about one of your neighbour</h1>
     <div class="pagination-wrapper">
     <%= will_paginate @posts, id: "aaa" %>
     </div>
    <%= render @posts %>
  </div>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<% if @post.errors.full_messages.any? %>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li>  <%= msg %></li>
  <% end %>
</ul>
<% end %>
<div class="row log-in">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@post) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </p>
  <p>
    <%= f.label :body, value: "Content" %>
    <%= f.text_area :body, size: "30x5", class: "form-control" %>
  </p>
 <p> <%= f.submit "Create", class: "submit-btn" %></p>
<% end %>
 </div>
</div>